version: '3.8'

services:
  

  # --- API Gateway ---
  api-gateway:
    build:
      context: .
      args:
        APP_NAME: api-gateway-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=api-gateway-app

  # --- COmmon Services Microservice ---
  common-service:
    build:
      context: .
      args:
        APP_NAME: common-service-app
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=common-service-app
      - PORT=4001
    ports:
      - "4001:4001"

  # --- User Microservice ---
  user-service:
    build:
      context: .
      args:
        APP_NAME: user-services-app
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=user-services-app
      - PORT=3002
    ports:
      - "3002:3002"