export const USER_SERVICES_PATTERN = {
    USER: {
        GET_EMAILS: { cmd: 'user_get_email' },
        CREATE_USER: { cmd: 'user_create' },
        LOGIN_USER: { cmd: 'user_login' },
        LOGIN_ADMIN: { cmd: 'user_admin' },
        GET_USER_INFO: { cmd: 'user_get_info' },
        GET_ALL_USERS: { cmd: 'user_get_all' },
        CREATE_ONBOARD_USER: { cmd: 'user_create_onboard' },
        SEND_ONBOARD_EMAIL: { cmd: 'user_send_onboard_email' },
        ADMIN_CREATE_USER: { cmd: 'admin_create_user' },
        ADMIN_UPDATE_USER: { cmd: 'admin_update_user' },
        GET_ME: { cmd: 'user_get_me' },
        CHANGE_PASSWORD: { cmd: 'user_change_password' },
        ONBOARD_LOGIN: { cmd: 'user_onboard_login' },
    },
    COMPANY: {
        CREATE: { cmd: 'company_create' },
        GET_ONE: { cmd: 'company_get_one' },
        GET_ALL: { cmd: 'company_get_all' },
        UPDATE: { cmd: 'company_update' },
        DELETE: { cmd: 'company_delete' },
    },
    ROLES: {
        CREATE: { cmd: 'role_create' },
        GET_ONE: { cmd: 'role_get_one' },
        GET_BY_COMPANY: { cmd: 'role_get_by_company' },
        UPDATE: { cmd: 'role_update' },
        DELETE: { cmd: 'role_delete' },
    },
    PERMISSIONS: {
        CREATE: { cmd: 'permission_create' },
        GET_ONE: { cmd: 'permission_get_one' },
        GET_ALL: { cmd: 'permission_get_all' },
        UPDATE: { cmd: 'permission_update' },
        DELETE: { cmd: 'permission_delete' },
    },
    ROLE_PERMISSIONS: {
        ASSIGN: { cmd: 'role_permission_assign' },
        REMOVE: { cmd: 'role_permission_remove' },
        GET_BY_ROLE: { cmd: 'role_permission_get_by_role' },
    },
    USER_ROLES: {
        ASSIGN: { cmd: 'user_role_assign' },
        REMOVE: { cmd: 'user_role_remove' },
        GET_BY_COMPANY_USER: { cmd: 'user_role_get_by_company_user' },
    },
    COMPANY_USER: {
        CREATE: { cmd: 'company_user_create' },
        GET_ONE: { cmd: 'company_user_get_one' },
        GET_ALL: { cmd: 'company_user_get_all' },
        GET_BY_COMPANY: { cmd: 'company_user_get_by_company' },
        GET_BY_USER: { cmd: 'company_user_get_by_user' },
        REMOVE: { cmd: 'company_user_remove' },
    },
    ONBOARDING_COMPANY: {
        CREATE: { cmd: 'onboarding_company_create' },
        GET_ONE: { cmd: 'onboarding_company_get_one' },
        GET_ALL: { cmd: 'onboarding_company_get_all' },
        GET_BY_USER: { cmd: 'onboarding_company_get_by_user' },
        UPDATE: { cmd: 'onboarding_company_update' },
        APPROVE: { cmd: 'onboarding_company_approve' },
        DELETE: { cmd: 'onboarding_company_delete' },
    },
    ONBOARDING_ATTACHMENT: {
        CREATE: { cmd: 'onboarding_attachment_create' },
        BULK_CREATE: { cmd: 'onboarding_attachment_bulk_create' },
        GET_BY_ONBOARDING: { cmd: 'onboarding_attachment_get_by_onboarding' },
        DELETE: { cmd: 'onboarding_attachment_delete' },
    },
    ONBOARDING_VERIFICATION: {
        CREATE: { cmd: 'onboarding_verification_create' },
        BULK_CREATE: { cmd: 'onboarding_verification_bulk_create' },
        GET_BY_ONBOARDING: { cmd: 'onboarding_verification_get_by_onboarding' },
        UPDATE: { cmd: 'onboarding_verification_update' },
        DELETE: { cmd: 'onboarding_verification_delete' },
    },
};

export const CALLING_SERVICE_PATTERNS = {
    CALL: {
        CREATE: { cmd: 'call_create' },
        GET_ONE: { cmd: 'call_get_one' },
        GET_ALL: { cmd: 'call_get_all' },
        JOIN: { cmd: 'call_join' },
        LEAVE: { cmd: 'call_leave' },
        END: { cmd: 'call_end' },
        GET_PARTICIPANTS: { cmd: 'call_get_participants' },
        UPDATE_SOCKET: { cmd: 'call_update_socket' },
        GET_ICE_SERVERS: { cmd: 'call_get_ice_servers' },
        GET_STATS: { cmd: 'call_get_stats' },
        GET_TURN_CONFIG: { cmd: 'call_get_turn_config' },
    },
    ONLINE_USER: {
        REGISTER: { cmd: 'online_user_register' },
        REMOVE: { cmd: 'online_user_remove' },
        GET_ALL: { cmd: 'online_user_get_all' },
        GET_ONE: { cmd: 'online_user_get_one' },
        UPDATE_LAST_SEEN: { cmd: 'online_user_update_last_seen' },
    },
};

export const COMMON_SERVICES_PATTERNS = {
    NOTIFICATION: {
        CREATE_BULK_NOTIFICATION: { cmd: 'notification_create_bulk' },
        BULK_CREATE_NOTIFICATION: { cmd: 'notification_bulk_create' },
        POST: { cmd: 'notification_post' },
        // New notification patterns
        GET_USER_NOTIFICATIONS: { cmd: 'notification_get_user_notifications' },
        GET_UNREAD_NOTIFICATIONS: { cmd: 'notification_get_unread' },
        GET_UNREAD_COUNT: { cmd: 'notification_get_unread_count' },
        MARK_AS_READ: { cmd: 'notification_mark_as_read' },
        CREATE_NOTIFICATION: { cmd: 'notification_create' },
        CREATE_ADMIN_BROADCAST: { cmd: 'notification_create_admin_broadcast' },
        CREATE_VENDOR_BROADCAST: { cmd: 'notification_create_vendor_broadcast' },
        APPROVE_BROADCAST: { cmd: 'notification_approve_broadcast' },
        GET_VENDOR_BROADCAST_REQUESTS: { cmd: 'notification_get_vendor_broadcast_requests' },
        GET_ADMIN_BROADCAST_HISTORY: { cmd: 'notification_get_admin_broadcast_history' },
        GET_VENDOR_CUSTOMERS_COUNT: { cmd: 'notification_get_vendor_customers_count' },
        GET_VENDOR_BROADCAST_HISTORY: { cmd: 'notification_get_vendor_broadcast_history' },
    },
    LOOKUP: {
        CREATE: { cmd: 'lookup_create' },
        GET_PARENT: { cmd: 'lookup_get_parent_child' },
        GET_ALL_PARENTS: { cmd: 'lookup_get_all_parent' },
        DELETE_ROW: { cmd: 'lookup_delete_row' }
    },
    LEADS: {
        CREATE: { cmd: 'leads_create' },
        GET_ONE: { cmd: 'leads_get_one' },
        GET_ALL: { cmd: 'leads_get_all' },
        UPDATE: { cmd: 'leads_update' },
        DELETE: { cmd: 'leads_delete' },
        SEND_ONBOARD_EMAIL: { cmd: 'leads_send_onboard_email' },
        CREATE_EVIDENCE: { cmd: 'leads_evidence_create' },
        GET_EVIDENCE: { cmd: 'leads_evidence_get' },
        DELETE_EVIDENCE: { cmd: 'leads_evidence_delete' },
    },
    // Add all your commands here
};

export const EARN_WAGES_PATTERNS = {
    ONBOARDING_FORM: {
        CREATE_ONBOARDING: { cmd: 'ew_onboarding_create' },
        GET_ONBOARDING_WITH_FORMS: { cmd: 'ew_onboarding_get_with_forms' },
        GET_ONBOARDING_BY_BUSINESS_TYPE: { cmd: 'ew_onboarding_get_by_business_type' },
        GET_ALL_ONBOARDINGS: { cmd: 'ew_onboarding_get_all' },
        CREATE_FORM: { cmd: 'ew_form_create' },
        GET_FORM: { cmd: 'ew_form_get_one' },
        GET_FORMS_BY_ONBOARDING: { cmd: 'ew_form_get_by_onboarding' },
        CREATE_FIELD_DEFINITION: { cmd: 'ew_field_def_create' },
        BULK_CREATE_FIELD_DEFINITIONS: { cmd: 'ew_field_def_bulk_create' },
        GET_FIELD_DEFINITIONS_BY_FORM: { cmd: 'ew_field_def_get_by_form' },
        CREATE_APPROVAL_POLICY: { cmd: 'ew_approval_policy_create' },
        BULK_CREATE_APPROVAL_POLICIES: { cmd: 'ew_approval_policy_bulk_create' },
        GET_APPROVAL_POLICIES_BY_FORM: { cmd: 'ew_approval_policy_get_by_form' },
    },
    ONBOARDING_SUBMISSION: {
        CREATE_SUBMISSION: { cmd: 'ew_submission_create' },
        GET_SUBMISSION: { cmd: 'ew_submission_get_one' },
        GET_ALL_SUBMISSIONS: { cmd: 'ew_submission_get_all' },
        SUBMIT_FORM: { cmd: 'ew_form_submission_submit' },
        SAVE_DRAFT: { cmd: 'ew_form_submission_save_draft' },
        GET_FORM_SUBMISSION: { cmd: 'ew_form_submission_get_one' },
        GET_FORM_SUBMISSIONS_BY_SUBMISSION: { cmd: 'ew_form_submission_get_by_submission' },
        SAVE_FIELD_VALUES: { cmd: 'ew_field_value_save' },
        GET_FIELD_VALUES: { cmd: 'ew_field_value_get_by_form_submission' },
        GET_FIELD_VALUES_BY_SUBMISSION: { cmd: 'ew_field_value_get_by_submission' },
        GET_SUBMISSION_BY_ONBOARDING_AND_USER: { cmd: 'ew_submission_get_by_onboarding_and_user' },
        UPSERT_FIELD_VALUES: { cmd: 'ew_field_value_upsert' },
        GET_ALL_SUBMISSIONS_WITH_LEADS: { cmd: 'ew_submission_get_all_with_leads' },
        GET_VALUES_FOR_ADMIN_BY_SUBMISSION_ID: { cmd: 'ew_field_value_get_for_admin_by_submission_id' },
    },
    ONBOARDING_APPROVALS: {
        GET_PENDING_BY_ROLE: { cmd: 'ew_approval_get_pending_by_role' },
        APPROVE: { cmd: 'ew_approval_approve' },
        REJECT: { cmd: 'ew_approval_reject' },
        GET_BY_FORM_SUBMISSION: { cmd: 'ew_approval_get_by_form_submission' },
    },
    ONBOARDING_EVIDENCE: {
        CREATE: { cmd: 'ew_evidence_create' },
        GET_BY_FIELD_VALUE: { cmd: 'ew_evidence_get_by_field_value' },
        DELETE: { cmd: 'ew_evidence_delete' },
    },
};